
export enum ActionBlockingStatus {
    NONE = 'NONE',
    FAILED_PURGE_BLOCK = 'FAILED_PURGE_BLOCK',
    AWAITING_PURGE_RESPONSE = 'AWAITING_PURGE_RESPONSE',
    AWAITING_TRIAL_RESPONSE = 'AWAITING_TRIAL_RESPONSE',
    AWAITING_TRIAL_VOTES = 'AWAITING_TRIAL_VOTES',
    AWAITING_CONDEMNATION_RESPONSE = 'AWAITING_CONDEMNATION_RESPONSE'
}
