
export enum PhaseType {
    NONE = 'NONE',
    CURES = 'CURES',
    PURGE = 'PURGE',
    SPY_INVESTIGATION = 'SPY_INVESTIGATION',
    HEALTH = 'HEALTH',
    FUNERAL_COMMISSION = 'FUNERAL_COMMISSION',
    REPLACEMENT = 'REPLACEMENT',
    REHABILITATION = 'REHABILITATION',
    PARADE = 'PARADE'
}
