
export enum TrialStatus {
    AWAITING_RESPONSE = 'AWAITING_RESPONSE',
    VOTING = 'VOTING',
    COUNTING = 'COUNTING',
    RESOLVED_ABSOLVED = 'RESOLVED_ABSOLVED',
    RESOLVED_CONVICTED = 'RESOLVED_CONVICTED',
    CANCELLED = 'CANCELLED'
}
